/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarResourcesRouteImport } from './../routes/_sidebar/resources'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarPersonasRouteImport } from './../routes/_sidebar/personas'
import { Route as SidebarPermissionsRouteImport } from './../routes/_sidebar/permissions'
import { Route as SidebarGroupsRouteImport } from './../routes/_sidebar/groups'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarResourcesRoute = SidebarResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarPersonasRoute = SidebarPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarPermissionsRoute = SidebarPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGroupsRoute = SidebarGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/groups': typeof SidebarGroupsRoute
  '/permissions': typeof SidebarPermissionsRoute
  '/personas': typeof SidebarPersonasRoute
  '/profile': typeof SidebarProfileRoute
  '/resources': typeof SidebarResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/groups': typeof SidebarGroupsRoute
  '/permissions': typeof SidebarPermissionsRoute
  '/personas': typeof SidebarPersonasRoute
  '/profile': typeof SidebarProfileRoute
  '/resources': typeof SidebarResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/groups': typeof SidebarGroupsRoute
  '/_sidebar/permissions': typeof SidebarPermissionsRoute
  '/_sidebar/personas': typeof SidebarPersonasRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/resources': typeof SidebarResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/permissions'
    | '/personas'
    | '/profile'
    | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/permissions'
    | '/personas'
    | '/profile'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/dashboard'
    | '/_sidebar/groups'
    | '/_sidebar/permissions'
    | '/_sidebar/personas'
    | '/_sidebar/profile'
    | '/_sidebar/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/resources': {
      id: '/_sidebar/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof SidebarResourcesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/personas': {
      id: '/_sidebar/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof SidebarPersonasRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/permissions': {
      id: '/_sidebar/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof SidebarPermissionsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/groups': {
      id: '/_sidebar/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof SidebarGroupsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarGroupsRoute: typeof SidebarGroupsRoute
  SidebarPermissionsRoute: typeof SidebarPermissionsRoute
  SidebarPersonasRoute: typeof SidebarPersonasRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarResourcesRoute: typeof SidebarResourcesRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarGroupsRoute: SidebarGroupsRoute,
  SidebarPermissionsRoute: SidebarPermissionsRoute,
  SidebarPersonasRoute: SidebarPersonasRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarResourcesRoute: SidebarResourcesRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
