"""
Default permissions matrix based on the Databricks blog:
https://www.databricks.com/discover/pages/access-control#technical

Maps 6 personas to their default permission levels across workspace resource types.
This is used to seed the PermissionTemplate table on first run.
"""

from .models import Persona, PermissionLevel, ResourceType

# The default permissions matrix: persona -> resource_type -> permission_level
# Based on the blog's recommended mapping for a DEV environment.
DEFAULT_PERMISSIONS_MATRIX: dict[Persona, dict[ResourceType, PermissionLevel]] = {
    Persona.ADMIN: {
        ResourceType.CLUSTERS: PermissionLevel.CAN_MANAGE,
        ResourceType.CLUSTER_POLICIES: PermissionLevel.CAN_USE,
        ResourceType.INSTANCE_POOLS: PermissionLevel.CAN_MANAGE,
        ResourceType.JOBS: PermissionLevel.CAN_MANAGE,
        ResourceType.PIPELINES: PermissionLevel.CAN_MANAGE,
        ResourceType.EXPERIMENTS: PermissionLevel.CAN_MANAGE,
        ResourceType.REGISTERED_MODELS: PermissionLevel.CAN_MANAGE,
        ResourceType.REPOS: PermissionLevel.CAN_MANAGE,
        ResourceType.SERVING_ENDPOINTS: PermissionLevel.CAN_MANAGE,
        ResourceType.WAREHOUSES: PermissionLevel.CAN_MANAGE,
        ResourceType.NOTEBOOKS: PermissionLevel.CAN_MANAGE,
        ResourceType.DIRECTORIES: PermissionLevel.CAN_MANAGE,
        ResourceType.DASHBOARDS: PermissionLevel.CAN_MANAGE,
        ResourceType.ALERTS: PermissionLevel.CAN_MANAGE,
        ResourceType.TOKENS: PermissionLevel.CAN_USE,
    },
    Persona.DATA_ENGINEER: {
        ResourceType.CLUSTERS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.CLUSTER_POLICIES: PermissionLevel.CAN_USE,
        ResourceType.INSTANCE_POOLS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.JOBS: PermissionLevel.CAN_VIEW,
        ResourceType.PIPELINES: PermissionLevel.CAN_VIEW,
        ResourceType.EXPERIMENTS: PermissionLevel.CAN_READ,
        ResourceType.REGISTERED_MODELS: PermissionLevel.CAN_READ,
        ResourceType.REPOS: PermissionLevel.CAN_EDIT,
        ResourceType.SERVING_ENDPOINTS: PermissionLevel.CAN_VIEW,
        ResourceType.WAREHOUSES: PermissionLevel.NO_PERMISSIONS,
        ResourceType.NOTEBOOKS: PermissionLevel.CAN_RUN,
        ResourceType.DIRECTORIES: PermissionLevel.CAN_RUN,
        ResourceType.DASHBOARDS: PermissionLevel.CAN_RUN,
        ResourceType.ALERTS: PermissionLevel.CAN_RUN,
        ResourceType.TOKENS: PermissionLevel.CAN_USE,
    },
    Persona.DATA_SCIENTIST: {
        ResourceType.CLUSTERS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.CLUSTER_POLICIES: PermissionLevel.CAN_USE,
        ResourceType.INSTANCE_POOLS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.JOBS: PermissionLevel.CAN_VIEW,
        ResourceType.PIPELINES: PermissionLevel.CAN_VIEW,
        ResourceType.EXPERIMENTS: PermissionLevel.CAN_EDIT,
        ResourceType.REGISTERED_MODELS: PermissionLevel.CAN_EDIT,
        ResourceType.REPOS: PermissionLevel.CAN_EDIT,
        ResourceType.SERVING_ENDPOINTS: PermissionLevel.CAN_VIEW,
        ResourceType.WAREHOUSES: PermissionLevel.NO_PERMISSIONS,
        ResourceType.NOTEBOOKS: PermissionLevel.CAN_RUN,
        ResourceType.DIRECTORIES: PermissionLevel.CAN_RUN,
        ResourceType.DASHBOARDS: PermissionLevel.CAN_RUN,
        ResourceType.ALERTS: PermissionLevel.CAN_RUN,
        ResourceType.TOKENS: PermissionLevel.CAN_USE,
    },
    Persona.ANALYST: {
        ResourceType.CLUSTERS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.CLUSTER_POLICIES: PermissionLevel.NO_PERMISSIONS,
        ResourceType.INSTANCE_POOLS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.JOBS: PermissionLevel.CAN_VIEW,
        ResourceType.PIPELINES: PermissionLevel.CAN_VIEW,
        ResourceType.EXPERIMENTS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.REGISTERED_MODELS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.REPOS: PermissionLevel.CAN_READ,
        ResourceType.SERVING_ENDPOINTS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.WAREHOUSES: PermissionLevel.CAN_USE,
        ResourceType.NOTEBOOKS: PermissionLevel.CAN_RUN,
        ResourceType.DIRECTORIES: PermissionLevel.CAN_RUN,
        ResourceType.DASHBOARDS: PermissionLevel.CAN_RUN,
        ResourceType.ALERTS: PermissionLevel.CAN_RUN,
        ResourceType.TOKENS: PermissionLevel.CAN_USE,
    },
    Persona.DEPLOYER: {
        ResourceType.CLUSTERS: PermissionLevel.CAN_MANAGE,
        ResourceType.CLUSTER_POLICIES: PermissionLevel.CAN_USE,
        ResourceType.INSTANCE_POOLS: PermissionLevel.CAN_MANAGE,
        ResourceType.JOBS: PermissionLevel.CAN_MANAGE,
        ResourceType.PIPELINES: PermissionLevel.CAN_MANAGE,
        ResourceType.EXPERIMENTS: PermissionLevel.CAN_MANAGE,
        ResourceType.REGISTERED_MODELS: PermissionLevel.CAN_MANAGE_PRODUCTION_VERSIONS,
        ResourceType.REPOS: PermissionLevel.CAN_MANAGE,
        ResourceType.SERVING_ENDPOINTS: PermissionLevel.CAN_MANAGE,
        ResourceType.WAREHOUSES: PermissionLevel.CAN_MANAGE,
        ResourceType.NOTEBOOKS: PermissionLevel.CAN_MANAGE,
        ResourceType.DIRECTORIES: PermissionLevel.CAN_MANAGE,
        ResourceType.DASHBOARDS: PermissionLevel.CAN_MANAGE,
        ResourceType.ALERTS: PermissionLevel.CAN_MANAGE,
        ResourceType.TOKENS: PermissionLevel.CAN_USE,
    },
    Persona.SUPPORT: {
        ResourceType.CLUSTERS: PermissionLevel.CAN_VIEW,
        ResourceType.CLUSTER_POLICIES: PermissionLevel.NO_PERMISSIONS,
        ResourceType.INSTANCE_POOLS: PermissionLevel.NO_PERMISSIONS,
        ResourceType.JOBS: PermissionLevel.CAN_VIEW,
        ResourceType.PIPELINES: PermissionLevel.CAN_VIEW,
        ResourceType.EXPERIMENTS: PermissionLevel.CAN_READ,
        ResourceType.REGISTERED_MODELS: PermissionLevel.CAN_READ,
        ResourceType.REPOS: PermissionLevel.CAN_READ,
        ResourceType.SERVING_ENDPOINTS: PermissionLevel.CAN_VIEW,
        ResourceType.WAREHOUSES: PermissionLevel.NO_PERMISSIONS,
        ResourceType.NOTEBOOKS: PermissionLevel.CAN_VIEW,
        ResourceType.DIRECTORIES: PermissionLevel.CAN_VIEW,
        ResourceType.DASHBOARDS: PermissionLevel.CAN_VIEW,
        ResourceType.ALERTS: PermissionLevel.CAN_VIEW,
        ResourceType.TOKENS: PermissionLevel.NO_PERMISSIONS,
    },
}
